#!/bin/bash
# =============================================
# SmartRE - Start Services (chạy mỗi lần Codespace khởi động)
# =============================================

cd /workspaces/Smart_real_estate_management_system 2>/dev/null || \
  cd /workspaces/smart-real-estate-management-system 2>/dev/null || \
  cd "$(dirname "$(dirname "$0")")" || true

WORK_DIR=$(pwd)
echo "🔄 Starting SmartRE services (workdir: $WORK_DIR)..."

# ── Load nvm / Node ────────────────────────────────────────────────────────
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
[ -s "/home/codespace/nvm/nvm.sh" ] && source "/home/codespace/nvm/nvm.sh"
export PATH="/home/codespace/nvm/current/bin:/usr/local/share/nvm/current/bin:$PATH"

# ── 1. PHP binary detection ────────────────────────────────────────────────
PHP_BIN=$(which php 2>/dev/null || echo "/usr/bin/php")
PHP_VER=$("$PHP_BIN" -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;" 2>/dev/null || echo "")
PHP_API=$("$PHP_BIN" -r "echo PHP_ZEND_MODULE_API_NO;" 2>/dev/null || echo "")
echo "  PHP binary : $PHP_BIN"
echo "  PHP version: $PHP_VER  (API: $PHP_API)"

# ── 2. Install pdo_mysql via apt ───────────────────────────────────────────
echo "📦 Ensuring pdo_mysql extension..."

if "$PHP_BIN" -m 2>/dev/null | grep -qi "pdo_mysql"; then
  echo "  ✅ pdo_mysql already loaded"
  PDO_MYSQL_READY=true
else
  echo "  Installing php${PHP_VER}-mysql via apt..."
  sudo apt-get install -y -qq "php${PHP_VER}-mysql" 2>/dev/null || true
  sudo apt-get install -y -qq php-mysql php-dev 2>/dev/null || true

  # Tìm pdo_mysql.so ở BẤT KỲ đâu trong hệ thống
  PDO_SO=$(find /usr/lib/php -name "pdo_mysql.so" 2>/dev/null | head -1)
  if [ -z "$PDO_SO" ]; then
    PDO_SO=$(find /usr -name "pdo_mysql.so" 2>/dev/null | head -1)
  fi

  if [ -n "$PDO_SO" ]; then
    echo "  ✅ Found pdo_mysql.so at: $PDO_SO"
    PDO_MYSQL_READY=true
  else
    echo "  ❌ pdo_mysql.so not found anywhere after apt install"
    PDO_MYSQL_READY=false
  fi
fi

# ── 3. Start MySQL ─────────────────────────────────────────────────────────
echo "🗄️  Starting MySQL..."
sudo service mysql start 2>/dev/null || true
sleep 2
sudo chmod 777 /var/run/mysqld 2>/dev/null || true
sudo chmod 777 /var/run/mysqld/mysqld.sock 2>/dev/null || true

MYSQL_READY=false
for i in {1..12}; do
  if sudo mysql -u root -e "SELECT 1" &>/dev/null 2>&1; then
    echo "  ✅ MySQL is ready"
    MYSQL_READY=true
    break
  fi
  echo "  Waiting for MySQL... ($i/12)"
  sleep 1
done

if [ "$MYSQL_READY" = true ]; then
  sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS smartre_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null || true
  sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ''; FLUSH PRIVILEGES;" 2>/dev/null || true
  sudo mysql -u root -e "CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY ''; GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION; FLUSH PRIVILEGES;" 2>/dev/null || true

  TABLE_COUNT=$(mysql -u root -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='smartre_db';" 2>/dev/null || echo "0")
  TABLE_COUNT=$(echo "$TABLE_COUNT" | tr -d '[:space:]')
  if [ "$TABLE_COUNT" = "0" ] || [ -z "$TABLE_COUNT" ]; then
    echo "  📦 Importing database schema..."
    mysql -u root smartre_db < database/smartre.sql 2>/dev/null && \
      echo "  ✅ Schema imported!" || echo "  ⚠️  Schema import had warnings"
  else
    echo "  ✅ Database OK ($TABLE_COUNT tables)"
  fi
fi

# ── 4. Kill old PHP server ─────────────────────────────────────────────────
pkill -f "php.*-S 0.0.0.0:8080" 2>/dev/null || true
sleep 1

# ── 5. Tạo php.ini tùy chỉnh để force-load pdo_mysql ─────────────────────
CUSTOM_INI="$WORK_DIR/.devcontainer/php-codespaces.ini"

# Lấy extension_dir mặc định của PHP
DEFAULT_EXT_DIR=$("$PHP_BIN" -r "echo ini_get('extension_dir');" 2>/dev/null || echo "")

cat > "$CUSTOM_INI" << INIEOF
[PHP]
; Force load pdo_mysql even if not in default extension_dir
; Auto-generated by start-services.sh
INIEOF

# Thêm pdo_mysql.so đường dẫn tuyệt đối nếu tìm thấy
if [ -n "$PDO_SO" ] && [ "$PDO_MYSQL_READY" = true ]; then
  echo "extension = $PDO_SO" >> "$CUSTOM_INI"
  echo "  ✅ php.ini configured with: extension = $PDO_SO"
fi

# Thêm extension_dir gốc để không mất các extensions khác
if [ -n "$DEFAULT_EXT_DIR" ]; then
  echo "extension_dir = $DEFAULT_EXT_DIR" >> "$CUSTOM_INI"
fi

# Show generated ini
echo "  📄 Generated $CUSTOM_INI:"
cat "$CUSTOM_INI"

# ── 6. Start PHP server với custom ini ────────────────────────────────────
echo "🚀 Starting PHP server on :8080..."
nohup "$PHP_BIN" -c "$CUSTOM_INI" -S 0.0.0.0:8080 -t "$WORK_DIR" > /tmp/php-server.log 2>&1 &
PHP_PID=$!
sleep 2

if kill -0 $PHP_PID 2>/dev/null; then
  # Verify pdo_mysql is loaded in the running server
  PDO_CHECK=$("$PHP_BIN" -c "$CUSTOM_INI" -r "echo in_array('mysql', PDO::getAvailableDrivers()) ? 'YES' : 'NO';" 2>/dev/null)
  echo "  ✅ PHP server running (PID $PHP_PID)"
  echo "  pdo_mysql loaded: $PDO_CHECK"
else
  echo "  ❌ PHP server failed! Log:"
  cat /tmp/php-server.log 2>/dev/null || true
fi

# ── 7. Ensure uploads folder permissions ──────────────────────────────────
mkdir -p uploads/properties uploads/users uploads/kyc
chmod -R 777 uploads/ 2>/dev/null || true

echo ""
echo "✅ Services ready! Run: npm run dev"
echo "   Debug API: /smart-real-estate-management-system/api/debug.php"
echo ""
