<?php
/**
 * SmartRE Debug Endpoint
 * Truy cập: /smart-real-estate-management-system/api/debug.php
 */
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');

$info = [
    'status'          => 'ok',
    'timestamp'       => date('Y-m-d H:i:s'),
    'php_version'     => PHP_VERSION,
    'php_binary'      => PHP_BINARY,
    'server_software' => $_SERVER['SERVER_SOFTWARE'] ?? 'unknown',
    'document_root'   => $_SERVER['DOCUMENT_ROOT'] ?? 'unknown',
];

// Check which system PHP binaries have pdo_mysql
$phpCandidates = ['/usr/bin/php8.3','/usr/bin/php8.2','/usr/bin/php8.1','/usr/bin/php'];
$phpBinaryInfo = [];
foreach ($phpCandidates as $bin) {
    if (file_exists($bin)) {
        $ver = shell_exec("$bin -r 'echo PHP_VERSION;' 2>/dev/null") ?? '';
        $hasMysql = (bool) shell_exec("$bin -m 2>/dev/null | grep -i pdo_mysql");
        $phpBinaryInfo[$bin] = ['version' => trim($ver), 'pdo_mysql' => $hasMysql];
    }
}
$info['system_php_binaries'] = $phpBinaryInfo;

// PHP ini info
$info['php_ini'] = [
    'loaded_file'   => php_ini_loaded_file() ?: '(none)',
    'scanned_files' => php_ini_scanned_files() ?: '(none)',
    'extension_dir' => ini_get('extension_dir'),
];

// PDO drivers
$info['pdo_drivers'] = PDO::getAvailableDrivers();

// Extensions
$info['extensions'] = [
    'pdo'       => extension_loaded('pdo'),
    'pdo_mysql' => extension_loaded('pdo_mysql'),
    'json'      => extension_loaded('json'),
    'mbstring'  => extension_loaded('mbstring'),
    'openssl'   => extension_loaded('openssl'),
];

// Find pdo_mysql.so on the system
$findResult = shell_exec('find /usr/lib/php -name "pdo_mysql.so" 2>/dev/null') ?? '';
$findResult2 = shell_exec('find /usr/local/lib/php -name "pdo_mysql.so" 2>/dev/null') ?? '';
$info['pdo_mysql_so_locations'] = array_filter(array_map('trim', array_merge(
    explode("\n", $findResult),
    explode("\n", $findResult2)
)));

// composer autoload
$autoloadPath = __DIR__ . '/../vendor/autoload.php';
$info['composer_autoload'] = file_exists($autoloadPath) ? 'found' : 'MISSING';

// .env file
$envPath = __DIR__ . '/../.env';
$info['env_file'] = file_exists($envPath) ? 'found' : 'MISSING';

// Custom ini (generated by start-services.sh)
$customIni = __DIR__ . '/../../.devcontainer/php-codespaces.ini';
$info['custom_ini'] = file_exists($customIni) ? file_get_contents($customIni) : 'NOT FOUND';

// DB config (from env vars)
$dbHost = getenv('DB_HOST') ?: 'localhost';
$dbName = getenv('DB_NAME') ?: 'smartre_db';
$dbUser = getenv('DB_USER') ?: 'root';
$dbPass = getenv('DB_PASS') ?: '';

$info['db_config'] = [
    'host' => $dbHost,
    'name' => $dbName,
    'user' => $dbUser,
];

// Database connection test
if (!extension_loaded('pdo_mysql')) {
    $info['db_status'] = 'SKIPPED: pdo_mysql not loaded';

    // Try to load it manually
    $soLocations = $info['pdo_mysql_so_locations'];
    foreach ($soLocations as $so) {
        if (file_exists($so)) {
            $loaded = @dl($so);
            if ($loaded && extension_loaded('pdo_mysql')) {
                $info['db_status_note'] = "Dynamically loaded from: $so";
                break;
            }
        }
    }
} else {
    try {
        $pdo = new PDO(
            "mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4",
            $dbUser, $dbPass,
            [PDO::ATTR_TIMEOUT => 3, PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
        $info['db_status']      = 'connected';
        $info['db_tables']      = $tables;
        $info['db_table_count'] = count($tables);
        if (in_array('users', $tables)) {
            $info['user_count'] = (int) $pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();
        }
    } catch (PDOException $e) {
        $info['db_status'] = 'ERROR: ' . $e->getMessage();
    }
}

// uploads dir
$info['uploads_dir'] = [
    'exists'   => is_dir(__DIR__ . '/../uploads'),
    'writable' => is_writable(__DIR__ . '/../uploads'),
];

// env vars
$info['env_vars'] = [
    'DB_HOST'     => getenv('DB_HOST') ?: '(not set)',
    'DB_NAME'     => getenv('DB_NAME') ?: '(not set)',
    'APP_ENV'     => getenv('APP_ENV') ?: '(not set)',
    'CODESPACES'  => getenv('CODESPACES') ?: '(not set)',
];

echo json_encode($info, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
